import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-red-500'>Lets Build a badass Portfolio!</h1>

      {/* Header */}

      {/* Hero */}

      {/* About */}

      {/* Experience */}
      
      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}
      

    </div>
  )
}
