import Head from 'next/head'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import styles from '../styles/Home.module.css'
import { ArrowUpTrayIcon } from '@heroicons/react/20/solid'

export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden 
    z-0 scroll-main'>
      <Head>
        <title>Gregory&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      <section id='about' className='snap-center'>
        <About />
      </section>

      <section id='projects' className='snap-start'>
        <Projects />
      </section>

      <section id='skills' className='snap-start'>
        <Skills />
      </section>

      <section id='experience' className='snap-center'>
        <Experience />
      </section>

      <section id='contact' className='snap-start'>
        <Contact />
      </section>

      <Link href='#hero'>
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex items-center justify-center'>
            <ArrowUpTrayIcon className='opacity-5 hover:opacity-40 duration-1000 ease-out transition-all h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer' />
          </div>
        </footer>
      </Link>

    </div>
  )
}
